export const menuItems=[
  {id:"fuji",category:"Rolls especiales",name:"Fuji",description:"Uramaki relleno de camarón, cangrejo, queso crema, con topping de aguacate y camarón crujiente, bañado en salsa de anguila y salsa fuji.",ingredients:["Camarón","Cangrejo","Queso crema","Aguacate","Camarón crujiente","Salsa de anguila","Salsa fuji"],price:13,pieces:null,image:null,source:"SRC-002 · pág. 10"},
  {id:"yuzu",category:"Rolls especiales",name:"Yuzu",description:"Uramaki relleno de tuna, mango, cebollín frito, con topping de pescado blanco y masago, bañado en salsa ponzu con un toque de limón.",ingredients:["Tuna","Mango","Cebollín frito","Pescado blanco","Masago","Salsa ponzu","Limón"],price:11,pieces:null,image:"public/media/roll-yuzu.webp",source:"SRC-002 · pág. 10",anatomy:{order:[3,4,1,2,0,5,6],main:4,points:[[32,29],[39,27],[28,47],[33,45],[27,58],[35,64],[36,33]]}},
  {id:"kamasutra",category:"Rolls especiales",name:"Kamasutra",description:"Envuelto en papel de soya, relleno de tuna, salmón, pescado blanco, camarón y kani crujiente con queso crema y aguacate, coronado con gratinado de pesca blanca crujiente.",ingredients:["Papel de soya","Tuna","Salmón","Pescado blanco","Camarón","Kani crujiente","Queso crema","Aguacate","Gratinado de pesca blanca crujiente"],price:14,pieces:null,image:null,source:"SRC-002 · pág. 11"},
  {id:"rendi",category:"Rolls especiales",name:"Rendi",description:"Envuelto en papel de soya, relleno de camarón, plátano, ensalada kani, wakame, aguacate y cebollín, con topping de salmón ahumado y mix de tuna blanca flameada, bañado en salsa de anguila y spicy mayo.",ingredients:["Papel de soya","Camarón","Plátano","Ensalada kani","Wakame","Aguacate","Cebollín","Salmón ahumado","Tuna blanca flameada","Salsa de anguila","Spicy mayo"],price:15,pieces:null,image:null,source:"SRC-002 · pág. 12"},
  {id:"sei",category:"Rolls especiales",name:"Sei Exclusive",description:"Uramaki relleno de camarón crujiente, aguacate y cilantro, con topping de tuna, slice de limón y masago, bañado en salsa de anguila.",ingredients:["Camarón crujiente","Aguacate","Cilantro","Tuna","Limón","Masago","Salsa de anguila"],price:11,pieces:"10 piezas",image:"public/media/roll-sei.webp",source:"SRC-002 · pág. 12",anatomy:{order:[4,3,6,0,2,1,5],main:3,points:[[38,28],[34,35],[27,45],[36,50],[29,58],[31,63],[41,29]]}},
  {id:"koga",category:"Rolls especiales",name:"Koga Explosion",description:"Uramaki relleno de cangrejo, tuna y cebollín, con topping de spicy tuna y cebolla frita, bañado en salsa de anguila.",ingredients:["Cangrejo","Tuna","Cebollín","Spicy tuna","Cebolla frita","Salsa de anguila"],price:11,pieces:"10 piezas",image:"public/media/roll-koga.webp",source:"SRC-002 · pág. 12",anatomy:{order:[4,5,0,2,1,3],main:2,points:[[32,29],[27,37],[36,43],[39,44],[33,55],[37,36]]}},
  {id:"playboy",category:"Rolls especiales",name:"Playboy",description:"Uramaki relleno de camarón, aguacate y pepino, con topping de tuna y masago, bañado en salsa de anguila y spicy mayo.",ingredients:["Camarón","Aguacate","Pepino","Tuna","Masago","Salsa de anguila","Spicy mayo"],price:10,pieces:"10 piezas",image:"public/media/roll-playboy.webp",source:"SRC-002 · pág. 12",anatomy:{order:[3,4,0,1,2,5,6],main:2,points:[[34,33],[39,28],[36,50],[30,62],[28,45],[27,41],[32,65]]}},
  {id:"nigiri-tuna",category:"Nigiris",name:"Nigiri Tuná",description:"Atún importado, decorado con cebolla crujiente y nuestra exclusiva salsa Ryo.",ingredients:["Arroz","Atún importado","Cebolla crujiente","Salsa Ryo"],price:5,pieces:"2 piezas",image:null,source:"SRC-002 · pág. 5"},
  {id:"nigiri-salmon",category:"Nigiris",name:"Nigiri Salmón",description:"Salmón flameado servido con spicy mayo.",ingredients:["Arroz","Salmón flameado","Spicy mayo"],price:5,pieces:"2 piezas",image:null,source:"SRC-002 · pág. 5"},
  {id:"pesca-blanca",category:"Nigiris",name:"Pesca Blanca",description:"Pescado blanco, decorado con slice de limón y salsa ponzu.",ingredients:["Arroz","Pescado blanco","Limón","Salsa ponzu"],price:5,pieces:"2 piezas",image:null,source:"SRC-002 · pág. 5"}
];
